services:
  rails:
    container_name: web
    # image: sorathun/ruby-on-rails-web:latest
    build: .
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
      - RAILS_MASTER_KEY=6e420a4daaa5d05029cf694862e73ae5
      - SECRET_KEY_BASE=$(bundle exec rails secret)
    command: bash -c "bundle exec rails db:create && bundle exec rails db:migrate && bundle exec rails server -p '3000' -b '0.0.0.0' "
